### ISSUE TITLE
expire must be supplied with priority=2

### ISSUE THREAD

**Issue by steinwedel** [qbit/node-pushover#14]
To send an emergency-priority notification, the priority parameter must be set to 2 and the retry and expire parameters must be supplied.
Currently expire and retry parameters are not supported.

**Comment by qbit** [comment]
All options are supported.. the [setDefaults](https://github.com/qbit/node-pushover/blob/master/lib/pushover.js#L116) function is just a suggestion.

```
var pri_msg = {
        message: 'omg hai pri',
        sound: 'magic',
        title: "emergency",
        expire: 3600,
        priority: 2,
        retry: 30
};
```

Setting the options will result in the expected behaviour.

**Comment by OleWissing** [comment]
Any news about High priority (With acknowledgement) messages?
Need it for smoke alarms and pir.
