### ISSUE TITLE
default sound setting is incorrect

### ISSUE THREAD

**Issue by Omniver** [qbit/node-pushover#15]
If no sound is specified for the alert , the module automatically sets the sound to "pushover" which is the default sound.  This is incorrect as it overrides the users 'default' sound and always plays the standard default sound even if the user has selected a different default in the app.    The proper handling for no specified sound is to not set one at all in the message to pushover, this lets the user's chosen default to be used.  

From the API Docs:

"If no sound parameter is specified, the user's default tone will play. If the user has not chosen a custom sound, the standard Pushover sound will play."

**Comment by qbit** [comment]
Thanks for the info!
