### ISSUE TITLE
reply back with full request data

### ISSUE THREAD

**Issue by jonferreira** [qbit/node-pushover#19]
Hi,

You should consider changing to

```
res.on('end', function() {
	    self.errors(data);
	    if (fn) {
		fn.call(null, err, res);
	    }
	});
```

and

```
req.on('error', function(err) {
	if (fn) {
	    fn.call(null, err, res);
	}
	// In the tests the "end" event did not get emitted if  "error" was emitted,
	// but to be sure that the callback is not get called twice, null the callback function
	fn = null;
    });
```

so that we can get the request headers and thus access to

```
x-limit-app-limit: ""
x-limit-app-remaining: ""
x-limit-app-reset: ""
```

**Comment by qbit** [comment]
Makes sense for `res.on('end'...`, but res isn't in scope for the `req.on('error'` bit..

I can add it to the `onerror` handler though. @jonferreira can you look at this branch https://github.com/qbit/node-pushover/tree/standard to see if it meets your needs?

**Comment by jonferreira** [comment]
yeah it does, thanks :)

**Comment by qbit** [comment]
Cool - I will cut a new release sometime today
