### ISSUE TITLE
missing @types/pushover-notifications

### ISSUE THREAD

**Issue by papakai** [qbit/node-pushover#21]
would be great to have that type definition package to be able to use it in a typescript development process. are there plans to get that released soon?

**Comment by qbit** [comment]
I don't use typescript. PRs welcome though!

**Comment by papakai** [comment]
Ehm, honestly - any update on your module would eventually enforce an update on this type declaration file then too. In general I am interested in supporting with a PR, but not in case periodically maintenance comes with it. So sorry, I will look then for alternatives.
