### ISSUE TITLE
Error: JSON parsing failed

### ISSUE THREAD

**Issue by jonasgroendahl** [qbit/node-pushover#27]
Trying to send a group of messages and randomly my program will crash and the error I get is "Error: JSON parsing failed":
```
{
  title: 'title',
  message: 'description',
  file: '/filepath'
}
```
The file is there, so that shouldn't be the problem.

Not sure where this comes from? Any ideas?

**Comment by jonasgroendahl** [comment]
Maybe it's because of sending 5 messages at the same time and then the API returns some nonsense JSON. could that be it?

**Comment by qbit** [comment]
Hard to say without seeing your code.

**Comment by jonasgroendahl** [comment]
after changing the code and console.logging instead of throwing the error, i get this:

<html>
<head><title>429 Too Many Requests</title></head>
<body>
<center><h1>429 Too Many Requests</h1></center>
<hr><center>nginx</center>
</body>
</html>

**Comment by qbit** [comment]
Ah, this is the same as #25 gonna close this one as dup.
