### ISSUE TITLE
Continuing issue #29

### ISSUE THREAD

**Issue by EdwardOak** [qbit/node-pushover#31]
I literally copy pasted your Read Me "Send a message" code and simply replaced with my tokens.

YOU have a syntax error.

Moving to npm 'chump' worked on first try.

**Comment by qbit** [comment]
Great.

**Comment by EdwardOak** [comment]
Right. Who cares about other anyways.

**Comment by qbit** [comment]
Listen. I can't help every person that has a syntax error - especially self-induced errors!

Move on. I don't have time to hand-hold.

**Comment by qbit** [comment]
Listen. I can't help every person that has a syntax error - especially self-induced errors!

Move on. I don't have time to hand-hold.
