### ISSUE TITLE
Error: application token is invalid

### ISSUE THREAD

**Issue by vreesie18** [qbit/node-pushover#32]
I followed your example but constantly I get an error message "Error: application token is invalid" while I am pretty sure both User and application keys are correct because I use them I a live environment with php and curl.

Any suggestion ?

var Push = require('pushover-notifications')

// send pushover

var p = new Push( {
	user: process.env['abcdef'],
	token: process.env['ghijkl'],
	debug: true
})

var msg = {
	// These values correspond to the parameters detailed on https://pushover.net/api
	// 'message' is required. All other values are optional.
	message: 'omg node test',	// required
	title: "EMA Monitor " + marketMode,
	sound: 'magic',
	device: 'OnePlus6T_Andre',
	priority: 1
}

p.send( msg, function( err, result ) {
	if ( err ) {
		throw err
	}
	console.log( result )
})

/nodejs/node_modules/pushover-notifications/lib/pushover.js:146
      throw new Error(d.errors[0], res)
      ^

Error: application token is invalid

**Comment by qbit** [comment]
With the above code in your shell you would need to “export abcdef=actualusertokenstring” and “export ghijkl=actualapplicationtokn”.

See https://nodejs.org/docs/latest-v13.x/api/process.html#process_process_env for more info.

**Comment by vreesie18** [comment]
Check, got it, works now. Many thanks. Love this world of people sharing their knowledge!
